from enum import Enum


class Department(str, Enum):
    NO_DEPARTMENT = ""
    ASEGURAMIENT_DE_CALIDAD = "ASEGURAMIENT_DE_CALIDAD"
    CONTROL_DE_CALIDAD = "CONTROL_DE_CALIDAD"
    INGENIERIA = "INGENIERIA"
    REGENCIA_TECNICA = "REGENCIA_TECNICA"
    SERVICIOS = "SERVICIOS"
    VALIDACIONES = "VALIDACIONES"
    PRODUCCION = "PRODUCCIÓN"
    OPEX = "OPEX"
    COMPRAS = "COMPRAS"
    COMERCIO_EXTERIOR = "COMERCIO_EXTERIOR"
    CONTABILIDA = "CONTABILIDAD"
    DESARROLLO_HUMANO = "DESARROLLO_HUMANO"
    PLANIFICACION = "PLANIFICACIÓN"
    DISENO = "DISEÑO"
    ALMACENES = "ALMACENES"
    SIMA = "SIMA"
    SEGURIDAD = "SEGURIDAD"
    DIRECCION_DE_OPERACIONES = "DIRECCION_DE_OPERACIONES"
