from enum import Enum


class Department(str, Enum):
    ASEGURAMIENT_DE_CALIDAD = "ASEGURAMIENT_DE_CALIDAD"
    CONTROL_DE_CALIDA = "CONTROL_DE_CALIDA"
    INGENIERIA = "INGENIERIA"
    REGENCIA_TECNICA = "REGENCIA_TECNICA"
    SERVICIOS = "SERVICIOS"
    VALIDACIONES = "VALIDACIONES"
    PRODUCCION = "PRODUCCION"
    OPEX = "OPEX"
    COMPRAS = "COMPRAS"
    COMERCIO_EXTERIOR = "COMERCIO_EXTERIOR"
    CONTABILIDA = "CONTABILIDA"
    DESARROLLO_HUMANO = "DESARROLLO_HUMANO"
    PLANIFICACION = "PLANIFICACION"
    DISENO = "DISENO"
    ALMACENES = "ALMACENES"
    SIMA = "SIMA"
    SEGURIDAD = "SEGURIDAD"
    DIRECCION_DE_OPERACIONES = "DIRECCION_DE_OPERACIONES"
