"""Problem in column Received

Revision ID: 5dc91ac40a55
Revises: 7486834449d1
Create Date: 2022-06-05 13:27:58.420409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dc91ac40a55'
down_revision = '7486834449d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('received', sa.String(length=25), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'received')
    # ### end Alembic commands ###
